// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import models "wu/models"

// ForecastPresenter is an autogenerated mock type for the ForecastPresenter type
type ForecastPresenter struct {
	mock.Mock
}

// Print provides a mock function with given fields: _a0
func (_m *ForecastPresenter) Print(_a0 []*models.ForecastDay) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]*models.ForecastDay) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
