// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import models "wu/models"

// ForecastRepository is an autogenerated mock type for the ForecastRepository type
type ForecastRepository struct {
	mock.Mock
}

// GetTenDayForecast provides a mock function with given fields: _a0
func (_m *ForecastRepository) GetTenDayForecast(_a0 string) ([]*models.ForecastDay, error) {
	ret := _m.Called(_a0)

	var r0 []*models.ForecastDay
	if rf, ok := ret.Get(0).(func(string) []*models.ForecastDay); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.ForecastDay)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
